name: Test action
on:
  schedule:
    # Every Monday at 00:00 UTC
    - cron: "0 0 * * 1"
  pull_request:
  push:
    branch:
      - main

  # Allows triggering the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      enable_ssh_access:
        type: boolean
        description: "Enable ssh access"
        required: false
        default: false

jobs:
  ssh:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15-intel
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run action
        uses: ./
      - name: Enable ssh access
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.enable_ssh_access }}
        with:
          limit-access-to-actor: true
      - name: Test multipass
        run: |
          multipass list
          multipass launch --name testy noble
          multipass exec testy -- cat /etc/os-release
          multipass delete --purge testy
          multipass list
      - name: Collect multipass log (Linux)
        if: ${{ always() && runner.os == 'Linux' }}
        run: |
          sudo journalctl --unit 'snap.multipass*' > ${{ runner.temp }}/multipass.log
      - name: Collect multipass log (macOS)
        if: ${{ always() && runner.os == 'macOS' }}
        run: |
          sudo cp /Library/Logs/Multipass/multipass.log ${{ runner.temp }}/multipass.log
          sudo chown "${USER}" ${{ runner.temp }}/multipass.log
      - name: Upload multipass log
        if: ${{ always() && runner.os == 'Linux' }}
        uses: actions/upload-artifact@v4
        with:
          name: multipass-log
          path: ${{ runner.temp }}/multipass.log
